#!/bin/sh
# Auto-bump build number and SW cache version on every commit

HOOK_DIR=$(dirname "$0")
powershell.exe -ExecutionPolicy RemoteSigned -File "$HOOK_DIR/../bump.ps1"
git add "$HOOK_DIR/../index.html" "$HOOK_DIR/../sw.js"
